
[window]
opacity = 1
padding.x = 3
padding.y = 3
decorations = "Full"
blur = true

[font]
size = 10.0
normal = { family = "FiraCode Nerd Font Mono", style = "Regular" }
bold = { family = "FiraCode Nerd Font Mono", style = "Medium" }

[general]
import = [
    "~/.config/alacritty/themes/themes/Google.toml"
]

# bindings = [{ <key>, <mods>, <mode>, <command> | <chars> | <action> },]
# key names --> https://docs.rs/winit/latest/winit/keyboard/enum.NamedKey.html
[keyboard]
bindings = [
	{ key="H", mods="Control", chars="\x1b[D" }, #ctrl + h --> left
	{ key="J", mods="Control", chars="\x1b[B" }, #ctrl j + --> down
	{ key="K", mods="Control", chars="\x1b[A" }, #ctrl k + --> up
	{ key="L", mods="Control", chars="\x1b[C" }, #ctrl l + --> right
	{ key="F", mods="Control", chars="\x1b[5~" }, #ctrl + F --> page up
	{ key="B", mods="Control", chars="\x1b[6~" }, #ctrl + B --> page down
]
