
[window]
opacity = 1
padding.x = 3
padding.y = 3
decorations = "Full"
blur = true

[font]
size = 10.0
normal = { family = "FiraCode Nerd Font Mono", style = "Regular" }
bold = { family = "FiraCode Nerd Font Mono", style = "Medium" }

[general]
import = [
    "~/.config/alacritty/themes/themes/Google.toml"
]
