# General config
set -g mouse on                 # mouse on
set -g allow-rename off         # prevent tmux from changing terminal title
set -g history-limit 75000     # increase scrollback buffer size

# Open the scratch pad
bind p display-popup -E "nvim ~/code/reference/notes/scratch"

# Prefix remapped from Ctrl-b to Ctrl-a
set -g prefix C-a
unbind C-b
bind C-a send-prefix

# detach and quit, in a smart way (for me)
unbind q
unbind Q
bind q detach-client
bind Q kill-session

# bind better pane resizing
bind -n -r S-up resize-pane -U 2
bind -n -r S-down resize-pane -D 2
bind -n -r S-left resize-pane -L 5
bind -n -r S-right resize-pane -R 5

# Other remaps
bind | split-window -h
bind - split-window -v 
bind r source-file ~/.tmux.conf; display "Reloaded."
unbind '"'
unbind %
