# General config
set -g mouse on                 # mouse on
set -g allow-rename off         # prevent tmux from changing terminal title
set -g history-limit 75000     # increase scrollback buffer size

# Open the scratch pad
bind p display-popup -E "nano -t -_ -S ~/code/reference/notes/scratch"

# Prefix remapped from Ctrl-b to Ctrl-a.
set -g prefix C-a
unbind C-b
bind C-a send-prefix

# detach and quit, in a smart way (for me)
unbind q
unbind Q
bind q detach-client
bind Q kill-session
bind w kill-pane

# bind better pane resizing
bind -n -r S-up resize-pane -U 2
bind -n -r S-down resize-pane -D 2
bind -n -r S-left resize-pane -L 5
bind -n -r S-right resize-pane -R 5

# Other remaps
bind | split-window -h
bind - split-window -v 
bind r source-file ~/.tmux.conf
unbind '"'
unbind '%'

#plugins
set -g @plugin 'plugins/tpm'
set -g @plugin 'plugins/tmux2k'
set -g @tmux2k-theme 'duo'

#theme
set -g @tmux2k-pane-border "#2E3440"
set -g @tmux2k-bg-main "#2E3440"
set -g @tmux2k-duo-fg "#1062ad"
set -g @tmux2k-duo-bg "#2E3440"

#bottom bar widgets
set -g @tmux2k-left-plugins "session cpu ram"
set -g @tmux2k-right-plugins "time"
set -g @tmux2k-window-list-alignment "absolute-centre"
set -g @tmux2k-window-list-compact "true"
#set -g @tmux2k-weather-scale "f"
#set -g @tmux2k-weather-location "55127"

run '~/.config/tmux/plugins/tpm/tpm'
